// packages/rsi-react-example/src/components/interpretation-manager.jsx

import React, { Component } from 'react';
import { RsiInterpretationManager } from '@akkadu/rsi-react'


const handleOnCreateEvent = (e) => {
  console.info('handleOnCreateEvent event:',e);
}

class InterpretationManager extends Component {

  render() {
    return (
      <div className="InterpretationManager">
        <h3> Interpretation Manager: </h3>
       <RsiInterpretationManager
           sdkKey="d9ed0b1e-6027-4c19-a43a-69b231713f1c"
           onReady = {handleOnCreateEvent}
        /> 
      </div>
    )
  }
}
export default InterpretationManager;

// packages/rsi-vue-example/src/components/interpretation-manager.vue
<template>
  <div class="wrapper">    
   <h2> Interpretation Manager Demo: </h2> 
    <RsiInterpretationManager
      sdkKey="d9ed0b1e-6027-4c19-a43a-69b231713f1c" 
      v-on:onCreateEvent="handleOnCreateEvent"/>
  </div>
</template>

<script>
import { RsiInterpretationManager } from '@akkadu/rsi-vue'  

export default {
  name: 'InterpretationManagerDemo',
  components: {
    RsiInterpretationManager
  },
  methods: {
    handleOnCreateEvent(e){
      console.info('handleOnCreateEvent event:',e);
    }
  },
}
</script>

<style>
.wrapper{
  margin-top: 3rem;
}
h2{
  padding-bottom: 1rem;
}

</style>
